apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-com
  namespace: example
spec:
  secretName: example-com-tls
  issuerRef:
    # If using a ClusterIssuer, uncomment this
    #kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - '*.example.com'
  - example.com
  - foo.com