apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  # If using a ClusterIssuer, change namespace to cert-manager
  namespace: example
type: Opaque
data:
  api-token: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwCg==
